[build]
  publish = "."
  command = "echo 'No build step required'"

[dev]
  command = "echo 'Development server ready'"
  port = 8888
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
